version: "3.8"

services:
  # SurrealDB (currently using in-memory, but can be configured for persistence)
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    command:
      - start
      - --log=info
      - --user=root
      - --pass=root
      - memory
    networks:
      - user-service-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # User Service (JSON-RPC API)
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user-service
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      surrealdb:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - DATABASE_URL=http://surrealdb:8000
    networks:
      - user-service-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Product Service (JSON-RPC API)
  product-service:
    build:
      context: .
      dockerfile: Dockerfile.product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      surrealdb:
        condition: service_healthy
    environment:
      - RUST_LOG=info
      - DATABASE_URL=http://surrealdb:8000
    networks:
      - user-service-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Gateway
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: gateway
    ports:
      - "8082:8082"
    depends_on:
      user-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
    environment:
      - RUST_LOG=info
    networks:
      - user-service-network
    restart: always

networks:
  user-service-network:
    driver: bridge

volumes:
  surrealdb-data:
